if(NOT DEFINED TEST_STUFFIT_DIRECT)
    message(FATAL_ERROR "TEST_STUFFIT_DIRECT is required")
endif()
if(NOT DEFINED DEMO_INSTALLER_DIR)
    message(FATAL_ERROR "DEMO_INSTALLER_DIR is required")
endif()
if(NOT DEFINED ORACLE_FILE)
    message(FATAL_ERROR "ORACLE_FILE is required")
endif()
if(NOT DEFINED WORK_DIR)
    set(WORK_DIR "${CMAKE_CURRENT_BINARY_DIR}/stuffit_demo_oracles")
endif()

if(NOT EXISTS "${ORACLE_FILE}")
    message(STATUS "StuffIt demo oracle file missing, skipping: ${ORACLE_FILE}")
    return()
endif()

if(CMAKE_VERSION VERSION_LESS 3.19)
    message(STATUS "CMake ${CMAKE_VERSION} lacks string(JSON), skipping StuffIt demo oracle test")
    return()
endif()

file(READ "${ORACLE_FILE}" oracle_json)
set(records)
string(JSON archive_count LENGTH "${oracle_json}" archives)
if(archive_count GREATER 0)
    math(EXPR last_archive "${archive_count} - 1")
else()
    set(last_archive -1)
endif()
foreach(archive_index RANGE 0 ${last_archive})
    string(JSON archive_name GET "${oracle_json}" archives ${archive_index} archive)
    string(JSON file_count LENGTH "${oracle_json}" archives ${archive_index} files)
    if(file_count GREATER 0)
        math(EXPR last_file "${file_count} - 1")
    else()
        set(last_file -1)
    endif()
    foreach(file_index RANGE 0 ${last_file})
        string(JSON expected_file GET "${oracle_json}" archives ${archive_index} files ${file_index} file)
        string(JSON expected_sha GET "${oracle_json}" archives ${archive_index} files ${file_index} sha256)
        string(JSON expected_size GET "${oracle_json}" archives ${archive_index} files ${file_index} size)
        list(APPEND records "${archive_name}|${expected_file}|${expected_sha}|${expected_size}")
    endforeach()
endforeach()

if(NOT records)
    message(FATAL_ERROR "No StuffIt demo oracle records found in ${ORACLE_FILE}")
endif()

file(REMOVE_RECURSE "${WORK_DIR}")
file(MAKE_DIRECTORY "${WORK_DIR}")
set(extracted_archives)
set(checked_count 0)
foreach(record IN LISTS records)
    string(REPLACE "|" ";" fields "${record}")
    list(GET fields 0 archive_name)
    list(GET fields 1 expected_file)
    list(GET fields 2 expected_sha)
    list(GET fields 3 expected_size)

    set(archive_path "${DEMO_INSTALLER_DIR}/${archive_name}")
    if(NOT EXISTS "${archive_path}")
        message(STATUS "StuffIt demo archive missing, skipping: ${archive_path}")
        continue()
    endif()

    string(MAKE_C_IDENTIFIER "${archive_name}" archive_id)
    set(output_dir "${WORK_DIR}/${archive_id}")
    list(FIND extracted_archives "${archive_name}" archive_index)
    if(archive_index EQUAL -1)
        file(REMOVE_RECURSE "${output_dir}")
        file(MAKE_DIRECTORY "${output_dir}")
        execute_process(
            COMMAND "${TEST_STUFFIT_DIRECT}" "${archive_path}" "${output_dir}"
            RESULT_VARIABLE extract_result
            OUTPUT_VARIABLE extract_stdout
            ERROR_VARIABLE extract_stderr)
        if(NOT extract_result EQUAL 0)
            message(FATAL_ERROR "In-tree StuffIt extraction failed for ${archive_name}\n${extract_stdout}\n${extract_stderr}")
        endif()
        list(APPEND extracted_archives "${archive_name}")
    endif()

    set(actual_path "${output_dir}/${expected_file}")
    if(NOT EXISTS "${actual_path}")
        message(FATAL_ERROR "Expected extracted file missing: ${archive_name} -> ${expected_file}")
    endif()
    file(SIZE "${actual_path}" actual_size)
    if(NOT actual_size STREQUAL expected_size)
        message(FATAL_ERROR "Size mismatch for ${archive_name} -> ${expected_file}: expected ${expected_size}, got ${actual_size}")
    endif()
    file(SHA256 "${actual_path}" actual_sha)
    string(TOLOWER "${actual_sha}" actual_sha)
    string(TOLOWER "${expected_sha}" expected_sha_lower)
    if(NOT actual_sha STREQUAL expected_sha_lower)
        message(FATAL_ERROR "SHA-256 mismatch for ${archive_name} -> ${expected_file}: expected ${expected_sha_lower}, got ${actual_sha}")
    endif()
    math(EXPR checked_count "${checked_count} + 1")
endforeach()

if(checked_count EQUAL 0)
    message(STATUS "No StuffIt demo oracle archives were present, skipping")
else()
    message(STATUS "Checked ${checked_count} StuffIt demo oracle files")
endif()