/*
 * test_stuffit_corpus.cpp - Desktop regression tests for classic StuffIt inputs.
 *
 * Loads committed JSON manifests generated by android/generate-stuffit-corpus-manifests.ps1
 * using desktop-side unar, then compares our listing and extraction behavior against them.
 */

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

#include <fstream>
#include <limits>
#include <string>
#include <vector>

#ifdef _WIN32
#include <fcntl.h>
#include <io.h>
#define stat_file _stat64
#define stat_t    struct __stat64
#else
#include <unistd.h>
#define stat_file stat
#define stat_t    struct stat
#endif

#include <nlohmann/json.hpp>

#include "sti2_extract.h"

using json = nlohmann::json;

#ifndef STUFFIT_TEST_FILES_DIR
#define STUFFIT_TEST_FILES_DIR "../../../../../../temp/stuffit-test-files"
#endif

#ifndef STUFFIT_MANIFEST_DIR
#define STUFFIT_MANIFEST_DIR "test/data/stuffit_manifests"
#endif

#define STUFFIT_BUILD_DIR            STUFFIT_TEST_FILES_DIR "/build"
#define SIT5_ENTRY_ID                0xa5a5a5a5u
#define SIT5_ARCHIVE_SIZE            100u
#define SIT5_ARCHIVE_VER             5u
#define SIT5_FLAG_DIR                0x40u
#define SIT5_FIXED_META_LEN          32u
#define SIT5_MAX_DEPTH               16
#define STUFFIT_SHA256_HEX_LEN       64
#define STUFFIT_MANIFEST_MAX_ENTRIES 32
#define STUFFIT_ARCHIVE_NAME_LEN     128

static const char *stuffit_archives[] = {
	"testfile.stuffit7.win.sit",
	"testfile.stuffit651_dlx.mac9.sit",
	"testfile.stuffit651_dlx.macx1.sit",
	"testfile.stuffit7_dlx.mac9.sit",
	"testfile.stuffit7_dlx.macx1.sit"
};

static const char *stuffit_method13_archives[] = {
	"testfile.stuffit45_dlx.mac9.sit"
};

static int tests_run;
static int tests_passed;

#define TEST(name)                \
	do {                          \
		tests_run++;              \
		printf("  %-50s ", name); \
		fflush(stdout);           \
	} while (0)

#define PASS()            \
	do {                  \
		tests_passed++;   \
		printf("PASS\n"); \
	} while (0)

#define FAIL(msg)                  \
	do {                           \
		printf("FAIL: %s\n", msg); \
	} while (0)

typedef struct {
	unsigned int next_offset;
	unsigned int child_offset;
	unsigned int child_count;
	int skip_entry;
	sti2_entry_t entry;
} sit5_parsed_entry_t;

typedef struct {
	char path[STI2_PATH_LEN];
	char sha256[STUFFIT_SHA256_HEX_LEN + 1];
	unsigned int size;
	unsigned int method;
	unsigned int archive_data_offset;
	unsigned int archive_data_length;
	int has_method;
	int has_archive_data_offset;
	int has_archive_data_length;
	int is_dir;
	int is_resource;
} stuffit_manifest_entry_t;

typedef struct {
	char archive_name[STUFFIT_ARCHIVE_NAME_LEN];
	stuffit_manifest_entry_t entries[STUFFIT_MANIFEST_MAX_ENTRIES];
	int num_entries;
} stuffit_manifest_t;

typedef struct {
	uint32_t state[8];
	uint64_t bit_count;
	unsigned char buffer[64];
	unsigned int buffer_len;
} sha256_ctx_t;

static unsigned int be16(const unsigned char *p)
{
	return ((unsigned int) p[0] << 8) | (unsigned int) p[1];
}

static unsigned int be32(const unsigned char *p)
{
	return ((unsigned int) p[0] << 24) |
	       ((unsigned int) p[1] << 16) |
	       ((unsigned int) p[2] << 8) |
	       (unsigned int) p[3];
}

static int file_exists(const char *path)
{
	stat_t st;

	return stat_file(path, &st) == 0;
}

static int read_binary_file(const char *path, std::vector<unsigned char> *out_buf)
{
	FILE *f;
	long len;

	if (!out_buf)
		return -1;
	out_buf->clear();

	f = fopen(path, "rb");
	if (!f)
		return -1;
	fseek(f, 0, SEEK_END);
	len = ftell(f);
	fseek(f, 0, SEEK_SET);
	if (len < 0) {
		fclose(f);
		return -1;
	}
	out_buf->resize((size_t) len);
	if ((size_t) len != 0 && fread(out_buf->data(), 1, (size_t) len, f) != (size_t) len) {
		out_buf->clear();
		fclose(f);
		return -1;
	}
	fclose(f);
	return 0;
}

static void path_join(char *out, int out_len, const char *a, const char *b)
{
	snprintf(out, out_len, "%s/%s", a, b);
}

static void sanitize_name(const char *src, char *dst, int dst_len)
{
	int out_len = 0;

	while (*src && out_len < dst_len - 1) {
		char c = *src++;

		if ((c >= 'a' && c <= 'z') ||
		    (c >= 'A' && c <= 'Z') ||
		    (c >= '0' && c <= '9') ||
		    c == '.' || c == '_')
			dst[out_len++] = c;
		else
			dst[out_len++] = '_';
	}

	dst[out_len] = '\0';
}

static int copy_string_to_buffer(const std::string &value, char *out, size_t out_len)
{
	if (!out || out_len == 0 || value.size() >= out_len)
		return -1;
	memcpy(out, value.c_str(), value.size() + 1u);
	return 0;
}

static int json_to_uint(const json &value, unsigned int *out)
{
	std::uint64_t raw_value;

	if (!out || (!value.is_number_unsigned() && !value.is_number_integer()))
		return -1;
	if (value.is_number_unsigned()) {
		raw_value = value.get<std::uint64_t>();
	} else {
		std::int64_t signed_value = value.get<std::int64_t>();

		if (signed_value < 0)
			return -1;
		raw_value = (std::uint64_t) signed_value;
	}
	if (raw_value > std::numeric_limits<unsigned int>::max())
		return -1;
	*out = (unsigned int) raw_value;
	return 0;
}

static int json_extract_optional_uint_field(const json &object, const char *key,
                                            unsigned int *out, int *has_value)
{
	json::const_iterator it;

	if (!key || !out || !has_value)
		return -1;
	*has_value = 0;
	*out = 0;
	it = object.find(key);
	if (it == object.end() || it->is_null())
		return 0;
	if (json_to_uint(*it, out) < 0)
		return -1;
	*has_value = 1;
	return 0;
}

static const uint32_t sha256_k[64] = {
	0x428a2f98u, 0x71374491u, 0xb5c0fbcfu, 0xe9b5dba5u,
	0x3956c25bu, 0x59f111f1u, 0x923f82a4u, 0xab1c5ed5u,
	0xd807aa98u, 0x12835b01u, 0x243185beu, 0x550c7dc3u,
	0x72be5d74u, 0x80deb1feu, 0x9bdc06a7u, 0xc19bf174u,
	0xe49b69c1u, 0xefbe4786u, 0x0fc19dc6u, 0x240ca1ccu,
	0x2de92c6fu, 0x4a7484aau, 0x5cb0a9dcu, 0x76f988dau,
	0x983e5152u, 0xa831c66du, 0xb00327c8u, 0xbf597fc7u,
	0xc6e00bf3u, 0xd5a79147u, 0x06ca6351u, 0x14292967u,
	0x27b70a85u, 0x2e1b2138u, 0x4d2c6dfcu, 0x53380d13u,
	0x650a7354u, 0x766a0abbu, 0x81c2c92eu, 0x92722c85u,
	0xa2bfe8a1u, 0xa81a664bu, 0xc24b8b70u, 0xc76c51a3u,
	0xd192e819u, 0xd6990624u, 0xf40e3585u, 0x106aa070u,
	0x19a4c116u, 0x1e376c08u, 0x2748774cu, 0x34b0bcb5u,
	0x391c0cb3u, 0x4ed8aa4au, 0x5b9cca4fu, 0x682e6ff3u,
	0x748f82eeu, 0x78a5636fu, 0x84c87814u, 0x8cc70208u,
	0x90befffau, 0xa4506cebu, 0xbef9a3f7u, 0xc67178f2u
};

static uint32_t sha256_rotr(uint32_t value, unsigned int bits)
{
	return (value >> bits) | (value << (32u - bits));
}

static void sha256_transform(sha256_ctx_t *ctx, const unsigned char block[64])
{
	uint32_t w[64];
	uint32_t a;
	uint32_t b;
	uint32_t c;
	uint32_t d;
	uint32_t e;
	uint32_t f;
	uint32_t g;
	uint32_t h;
	int i;

	for (i = 0; i < 16; i++) {
		w[i] = ((uint32_t) block[i * 4] << 24) |
		       ((uint32_t) block[i * 4 + 1] << 16) |
		       ((uint32_t) block[i * 4 + 2] << 8) |
		       (uint32_t) block[i * 4 + 3];
	}
	for (i = 16; i < 64; i++) {
		uint32_t s0 = sha256_rotr(w[i - 15], 7) ^ sha256_rotr(w[i - 15], 18) ^ (w[i - 15] >> 3);
		uint32_t s1 = sha256_rotr(w[i - 2], 17) ^ sha256_rotr(w[i - 2], 19) ^ (w[i - 2] >> 10);

		w[i] = w[i - 16] + s0 + w[i - 7] + s1;
	}

	a = ctx->state[0];
	b = ctx->state[1];
	c = ctx->state[2];
	d = ctx->state[3];
	e = ctx->state[4];
	f = ctx->state[5];
	g = ctx->state[6];
	h = ctx->state[7];

	for (i = 0; i < 64; i++) {
		uint32_t s1 = sha256_rotr(e, 6) ^ sha256_rotr(e, 11) ^ sha256_rotr(e, 25);
		uint32_t ch = (e & f) ^ ((~e) & g);
		uint32_t temp1 = h + s1 + ch + sha256_k[i] + w[i];
		uint32_t s0 = sha256_rotr(a, 2) ^ sha256_rotr(a, 13) ^ sha256_rotr(a, 22);
		uint32_t maj = (a & b) ^ (a & c) ^ (b & c);
		uint32_t temp2 = s0 + maj;

		h = g;
		g = f;
		f = e;
		e = d + temp1;
		d = c;
		c = b;
		b = a;
		a = temp1 + temp2;
	}

	ctx->state[0] += a;
	ctx->state[1] += b;
	ctx->state[2] += c;
	ctx->state[3] += d;
	ctx->state[4] += e;
	ctx->state[5] += f;
	ctx->state[6] += g;
	ctx->state[7] += h;
}

static void sha256_init(sha256_ctx_t *ctx)
{
	memset(ctx, 0, sizeof(*ctx));
	ctx->state[0] = 0x6a09e667u;
	ctx->state[1] = 0xbb67ae85u;
	ctx->state[2] = 0x3c6ef372u;
	ctx->state[3] = 0xa54ff53au;
	ctx->state[4] = 0x510e527fu;
	ctx->state[5] = 0x9b05688cu;
	ctx->state[6] = 0x1f83d9abu;
	ctx->state[7] = 0x5be0cd19u;
}

static void sha256_update(sha256_ctx_t *ctx, const unsigned char *data, size_t len)
{
	while (len > 0) {
		size_t copy_len = 64u - ctx->buffer_len;

		if (copy_len > len)
			copy_len = len;
		memcpy(ctx->buffer + ctx->buffer_len, data, copy_len);
		ctx->buffer_len += (unsigned int) copy_len;
		ctx->bit_count += (uint64_t) copy_len * 8u;
		data += copy_len;
		len -= copy_len;
		if (ctx->buffer_len == 64u) {
			sha256_transform(ctx, ctx->buffer);
			ctx->buffer_len = 0;
		}
	}
}

static void sha256_final(sha256_ctx_t *ctx, unsigned char digest[32])
{
	unsigned int i;

	ctx->buffer[ctx->buffer_len++] = 0x80u;
	if (ctx->buffer_len > 56u) {
		while (ctx->buffer_len < 64u)
			ctx->buffer[ctx->buffer_len++] = 0u;
		sha256_transform(ctx, ctx->buffer);
		ctx->buffer_len = 0;
	}
	while (ctx->buffer_len < 56u)
		ctx->buffer[ctx->buffer_len++] = 0u;
	for (i = 0; i < 8; i++)
		ctx->buffer[56u + i] = (unsigned char) (ctx->bit_count >> (56u - i * 8u));
	sha256_transform(ctx, ctx->buffer);
	for (i = 0; i < 8; i++) {
		digest[i * 4] = (unsigned char) (ctx->state[i] >> 24);
		digest[i * 4 + 1] = (unsigned char) (ctx->state[i] >> 16);
		digest[i * 4 + 2] = (unsigned char) (ctx->state[i] >> 8);
		digest[i * 4 + 3] = (unsigned char) ctx->state[i];
	}
}

static int sha256_file(const char *path, char out_hex[STUFFIT_SHA256_HEX_LEN + 1])
{
	FILE *f;
	sha256_ctx_t ctx;
	unsigned char buf[4096];
	unsigned char digest[32];
	size_t nread;
	static const char hex[] = "0123456789abcdef";
	int i;

	f = fopen(path, "rb");
	if (!f)
		return -1;
	sha256_init(&ctx);
	for (;;) {
		nread = fread(buf, 1, sizeof(buf), f);
		if (nread > 0)
			sha256_update(&ctx, buf, nread);
		if (nread < sizeof(buf)) {
			if (ferror(f)) {
				fclose(f);
				return -1;
			}
			break;
		}
	}
	fclose(f);
	sha256_final(&ctx, digest);
	for (i = 0; i < 32; i++) {
		out_hex[i * 2] = hex[digest[i] >> 4];
		out_hex[i * 2 + 1] = hex[digest[i] & 0x0f];
	}
	out_hex[STUFFIT_SHA256_HEX_LEN] = '\0';
	return 0;
}

static int manifest_load(const char *path, stuffit_manifest_t *out)
{
	std::ifstream input(path, std::ios::binary);

	if (!path || !out)
		return -1;
	memset(out, 0, sizeof(*out));
	if (!input.is_open())
		return -1;

	try {
		json document = json::parse(input);
		json::const_iterator archive_name_it;
		json::const_iterator entries_it;
		json::const_iterator entry_it;

		if (!document.is_object())
			return -1;
		archive_name_it = document.find("archive_name");
		entries_it = document.find("entries");
		if (archive_name_it == document.end() || !archive_name_it->is_string() ||
		    entries_it == document.end() || !entries_it->is_array())
			return -1;
		if (copy_string_to_buffer(archive_name_it->get<std::string>(),
		                          out->archive_name, sizeof(out->archive_name)) < 0)
			return -1;

		for (entry_it = entries_it->begin(); entry_it != entries_it->end(); ++entry_it) {
			const json &entry_json = *entry_it;
			json::const_iterator path_it;
			json::const_iterator kind_it;
			json::const_iterator size_it;
			json::const_iterator sha_it;
			stuffit_manifest_entry_t *entry;
			std::string kind;

			if (!entry_json.is_object() || out->num_entries >= STUFFIT_MANIFEST_MAX_ENTRIES)
				return -1;
			path_it = entry_json.find("path");
			kind_it = entry_json.find("kind");
			size_it = entry_json.find("size");
			sha_it = entry_json.find("sha256");
			if (path_it == entry_json.end() || !path_it->is_string() ||
			    kind_it == entry_json.end() || !kind_it->is_string() ||
			    size_it == entry_json.end() ||
			    sha_it == entry_json.end())
				return -1;

			entry = &out->entries[out->num_entries];
			memset(entry, 0, sizeof(*entry));
			if (copy_string_to_buffer(path_it->get<std::string>(),
			                          entry->path, sizeof(entry->path)) < 0 ||
			    json_to_uint(*size_it, &entry->size) < 0 ||
			    json_extract_optional_uint_field(entry_json, "method",
			                                     &entry->method, &entry->has_method) < 0 ||
			    json_extract_optional_uint_field(entry_json, "archive_data_offset",
			                                     &entry->archive_data_offset,
			                                     &entry->has_archive_data_offset) < 0 ||
			    json_extract_optional_uint_field(entry_json, "archive_data_length",
			                                     &entry->archive_data_length,
			                                     &entry->has_archive_data_length) < 0)
				return -1;

			if (sha_it->is_null()) {
				entry->sha256[0] = '\0';
			} else if (!sha_it->is_string() ||
			           copy_string_to_buffer(sha_it->get<std::string>(),
			                                 entry->sha256, sizeof(entry->sha256)) < 0) {
				return -1;
			}

			kind = kind_it->get<std::string>();
			entry->is_dir = kind == "directory";
			entry->is_resource = kind == "resource";
			out->num_entries++;
		}
	} catch (const json::exception &) {
		return -1;
	}

	return out->num_entries > 0 ? 0 : -1;
}

static int sit5_is_archive(const unsigned char *archive_data, size_t archive_size)
{
	const char *match = "StuffIt (c)1997-\377\377\377\377 Aladdin Systems, Inc., http://www.aladdinsys.com/StuffIt/\r\n";

	if (!archive_data || archive_size < SIT5_ARCHIVE_SIZE)
		return 0;
	while (*match) {
		if (*match != '\377' && *archive_data != (unsigned char) *match)
			return 0;
		match++;
		archive_data++;
	}
	return archive_data[2] == SIT5_ARCHIVE_VER;
}

static int sit5_build_path(const char *parent, const unsigned char *name_bytes,
                           unsigned int name_len, char *out, int out_len)
{
	char name[STI2_PATH_LEN];
	unsigned int i;
	int name_out = 0;

	for (i = 0; i < name_len && name_out < (int) sizeof(name) - 1; i++) {
		unsigned char c = name_bytes[i];

		if (c == '/' || c == '\\')
			name[name_out++] = '_';
		else if (c >= 32 && c <= 126)
			name[name_out++] = (char) c;
		else
			name[name_out++] = '?';
	}
	name[name_out] = '\0';

	if (!parent || !parent[0])
		snprintf(out, out_len, "%s", name);
	else
		snprintf(out, out_len, "%s/%s", parent, name);

	return out[0] ? 0 : -1;
}

static int sit5_parse_entry(const unsigned char *archive_data, size_t archive_size,
                            unsigned int entry_offset, const char *parent,
                            sit5_parsed_entry_t *out)
{
	unsigned int header_size;
	unsigned int name_len;
	unsigned int data_len;
	unsigned int comp_len;
	unsigned int metadata_offset;
	unsigned int payload_offset;
	unsigned int payload_limit;
	unsigned int child_count = 0;
	int is_dir;

	if (!archive_data || !out || entry_offset + 48u > archive_size)
		return -1;
	if (be32(archive_data + entry_offset) != SIT5_ENTRY_ID)
		return -1;
	if (archive_data[entry_offset + 4] != 1u && archive_data[entry_offset + 4] != 3u)
		return -1;

	memset(out, 0, sizeof(*out));
	header_size = be16(archive_data + entry_offset + 6);
	name_len = be16(archive_data + entry_offset + 30);
	data_len = be32(archive_data + entry_offset + 34);
	comp_len = be32(archive_data + entry_offset + 38);
	is_dir = (archive_data[entry_offset + 9] & SIT5_FLAG_DIR) != 0;

	if (header_size < 48u || entry_offset + header_size > archive_size)
		return -1;
	if (name_len > 31u || entry_offset + 48u + name_len > entry_offset + header_size)
		return -1;

	out->next_offset = be32(archive_data + entry_offset + 22);
	if (out->next_offset != 0 && out->next_offset >= archive_size)
		return -1;

	if (is_dir) {
		child_count = be16(archive_data + entry_offset + 46);
		if (data_len == 0xffffffffu) {
			out->skip_entry = 1;
			return 0;
		}
	}

	metadata_offset = entry_offset + header_size;
	if (metadata_offset + SIT5_FIXED_META_LEN > archive_size)
		return -1;
	payload_offset = metadata_offset + SIT5_FIXED_META_LEN;
	payload_limit = out->next_offset != 0u ? out->next_offset : (unsigned int) archive_size;

	if (payload_offset > archive_size || payload_limit > archive_size)
		return -1;
	if (!is_dir) {
		if (payload_limit < comp_len)
			return -1;
		payload_offset = payload_limit - comp_len;
		if (payload_offset < metadata_offset + SIT5_FIXED_META_LEN)
			return -1;
	}

	if (sit5_build_path(parent, archive_data + entry_offset + 48, name_len,
	                    out->entry.path, sizeof(out->entry.path)) < 0)
		return -1;

	out->entry.header_offset = entry_offset;
	out->entry.data_offset = payload_offset;
	out->entry.compressed_size = comp_len;
	out->entry.uncompressed_size = data_len;
	out->entry.resource_offset = 0u;
	out->entry.resource_compressed_size = 0u;
	out->entry.resource_uncompressed_size = 0u;
	out->entry.data_method = is_dir ? 0u : archive_data[entry_offset + 46];
	out->entry.resource_method = 0u;
	out->entry.file_type = be32(archive_data + metadata_offset + 4);
	out->entry.creator = be32(archive_data + metadata_offset + 8);
	out->entry.finder_flags = be16(archive_data + metadata_offset + 12);
	out->entry.is_directory = is_dir;
	out->child_count = child_count;
	out->child_offset = metadata_offset + SIT5_FIXED_META_LEN;
	return 0;
}

static int sit5_parse_entries(const unsigned char *archive_data, size_t archive_size,
                              unsigned int entry_offset, unsigned int entry_count,
                              const char *parent, sti2_entry_list_t *out,
                              int depth)
{
	unsigned int current_offset = entry_offset;
	unsigned int i;

	if (depth > SIT5_MAX_DEPTH)
		return -1;

	for (i = 0; i < entry_count; i++) {
		sit5_parsed_entry_t parsed;

		if (sit5_parse_entry(archive_data, archive_size, current_offset, parent, &parsed) < 0)
			return -1;
		if (!parsed.skip_entry) {
			if (out->num_entries >= STI2_MAX_ENTRIES)
				return -1;
			out->entries[out->num_entries++] = parsed.entry;
			if (parsed.entry.is_directory && parsed.child_count > 0) {
				if (sit5_parse_entries(archive_data, archive_size,
				                       parsed.child_offset, parsed.child_count,
				                       parsed.entry.path, out, depth + 1) < 0)
					return -1;
			}
		}
		if (i + 1u < entry_count) {
			if (parsed.next_offset == 0)
				return -1;
			current_offset = parsed.next_offset;
		}
	}

	return 0;
}

static int sit5_list_entries(const unsigned char *archive_data, size_t archive_size,
                             sti2_entry_list_t *out)
{
	unsigned int root_count;
	unsigned int first_offset;

	if (!out || !sit5_is_archive(archive_data, archive_size))
		return -1;

	memset(out, 0, sizeof(*out));
	root_count = be16(archive_data + 92);
	first_offset = be32(archive_data + 94);
	out->declared_file_count = root_count;
	out->declared_total_size = (unsigned int) archive_size;
	if (root_count == 0u || first_offset >= archive_size)
		return -1;
	if (sit5_parse_entries(archive_data, archive_size, first_offset, root_count,
	                       "", out, 0) < 0)
		return -1;

	return out->num_entries;
}

static int build_archive_path(char *out, int out_len, const char *archive_name)
{
	path_join(out, out_len, STUFFIT_BUILD_DIR, archive_name);
	return file_exists(out) ? 0 : -1;
}

static int build_manifest_path(char *out, int out_len, const char *archive_name)
{
	snprintf(out, out_len, "%s/%s.json", STUFFIT_MANIFEST_DIR, archive_name);
	return file_exists(out) ? 0 : -1;
}

static int load_archive_and_manifest(const char *archive_name,
                                     std::vector<unsigned char> *archive_data,
                                     sti2_entry_list_t *list,
                                     stuffit_manifest_t *manifest)
{
	char archive_path[1024];
	char manifest_path[1024];

	if (build_archive_path(archive_path, sizeof(archive_path), archive_name) < 0 ||
	    build_manifest_path(manifest_path, sizeof(manifest_path), archive_name) < 0 ||
	    read_binary_file(archive_path, archive_data) < 0 ||
	    sit5_list_entries(archive_data->data(), archive_data->size(), list) < 0 ||
	    manifest_load(manifest_path, manifest) < 0)
		return -1;
	if (strcmp(manifest->archive_name, archive_name) != 0)
		return -1;
	return 0;
}

static int load_archive_and_manifest_only(const char *archive_name,
                                          std::vector<unsigned char> *archive_data,
                                          stuffit_manifest_t *manifest)
{
	char archive_path[1024];
	char manifest_path[1024];

	if (build_archive_path(archive_path, sizeof(archive_path), archive_name) < 0 ||
	    build_manifest_path(manifest_path, sizeof(manifest_path), archive_name) < 0 ||
	    read_binary_file(archive_path, archive_data) < 0 ||
	    manifest_load(manifest_path, manifest) < 0)
		return -1;
	if (strcmp(manifest->archive_name, archive_name) != 0)
		return -1;
	return 0;
}

static void build_manifest_driven_entry(const stuffit_manifest_entry_t *manifest_entry,
                                        sti2_entry_t *entry)
{
	memset(entry, 0, sizeof(*entry));
	snprintf(entry->path, sizeof(entry->path), "%s", manifest_entry->path);
	entry->data_offset = manifest_entry->archive_data_offset;
	entry->compressed_size = manifest_entry->archive_data_length;
	entry->uncompressed_size = manifest_entry->size;
	entry->data_method = manifest_entry->method;
	entry->is_directory = 0;
}

static int run_manifest_fixture_test(void)
{
	int i;

	TEST("stuffit_manifest_fixtures_present");
	for (i = 0; i < (int) (sizeof(stuffit_archives) / sizeof(stuffit_archives[0])); i++) {
		char manifest_path[1024];

		if (build_manifest_path(manifest_path, sizeof(manifest_path), stuffit_archives[i]) < 0) {
			FAIL("manifest fixture missing");
			return 0;
		}
	}
	for (i = 0; i < (int) (sizeof(stuffit_method13_archives) / sizeof(stuffit_method13_archives[0])); i++) {
		char manifest_path[1024];

		if (build_manifest_path(manifest_path, sizeof(manifest_path), stuffit_method13_archives[i]) < 0) {
			FAIL("method 13 manifest fixture missing");
			return 0;
		}
	}
	PASS();
	return 1;
}

static int run_manifest_listing_test(void)
{
	int archive_index;
	int compared_entries = 0;

	TEST("stuffit_listing_matches_manifest_entries");
	for (archive_index = 0; archive_index < (int) (sizeof(stuffit_archives) / sizeof(stuffit_archives[0])); archive_index++) {
		std::vector<unsigned char> archive_data;
		stuffit_manifest_t manifest;
		sti2_entry_list_t list;
		int i;

		if (load_archive_and_manifest(stuffit_archives[archive_index], &archive_data,
		                              &list, &manifest) < 0) {
			FAIL("could not load archive or manifest");
			return 0;
		}
		for (i = 0; i < manifest.num_entries; i++) {
			int index;

			if (manifest.entries[i].is_resource)
				continue;
			index = sti2_find_entry_index(&list, manifest.entries[i].path);
			if (index < 0) {
				FAIL("manifest entry missing from listing");
				return 0;
			}
			if (manifest.entries[i].is_dir) {
				if (!list.entries[index].is_directory) {
					FAIL("manifest directory listed as file");
					return 0;
				}
			} else if (list.entries[index].is_directory ||
			           list.entries[index].uncompressed_size != manifest.entries[i].size) {
				FAIL("manifest file metadata mismatch");
				return 0;
			}
			compared_entries++;
		}
	}
	if (compared_entries == 0) {
		FAIL("no manifest entries compared");
		return 0;
	}
	PASS();
	return 1;
}

static int is_supported_stuffit_method(unsigned int method)
{
	return method == 0u || method == 13u || method == 14u || method == 15u;
}

static int run_manifest_supported_hash_test(void)
{
	int archive_index;
	int supported_count = 0;

	TEST("stuffit_supported_hashes_match_manifest");
	for (archive_index = 0; archive_index < (int) (sizeof(stuffit_archives) / sizeof(stuffit_archives[0])); archive_index++) {
		std::vector<unsigned char> archive_data;
		stuffit_manifest_t manifest;
		sti2_entry_list_t list;
		int i;

		if (load_archive_and_manifest(stuffit_archives[archive_index], &archive_data,
		                              &list, &manifest) < 0) {
			FAIL("could not load archive or manifest");
			return 0;
		}
		for (i = 0; i < manifest.num_entries; i++) {
			char temp_name[256];
			char actual_path[1024];
			char actual_sha256[STUFFIT_SHA256_HEX_LEN + 1];
			int index;
			int written;

			if (manifest.entries[i].is_dir || manifest.entries[i].is_resource)
				continue;
			index = sti2_find_entry_index(&list, manifest.entries[i].path);
			if (index < 0) {
				FAIL("manifest data entry missing from listing");
				return 0;
			}
			if (!is_supported_stuffit_method(list.entries[index].data_method))
				continue;
			if (!manifest.entries[i].sha256[0]) {
				FAIL("supported manifest entry missing hash");
				return 0;
			}

			supported_count++;
			sanitize_name(manifest.entries[i].path, temp_name, sizeof(temp_name));
			snprintf(actual_path, sizeof(actual_path), "test_stuffit_%d_%s.bin",
			         archive_index, temp_name);
			written = sti2_extract_entry(archive_data.data(), archive_data.size(),
			                             &list.entries[index], actual_path);
			if (written < 0 || (unsigned int) written != manifest.entries[i].size ||
			    sha256_file(actual_path, actual_sha256) < 0 ||
			    strcmp(actual_sha256, manifest.entries[i].sha256) != 0) {
				remove(actual_path);
				FAIL("supported entry hash mismatch");
				return 0;
			}
			remove(actual_path);
		}
	}
	if (supported_count == 0) {
		FAIL("no supported entries hashed");
		return 0;
	}
	PASS();
	return 1;
}

static int run_manifest_unsupported_test(void)
{
	int archive_index;
	int unsupported_count = 0;

	TEST("stuffit_unsupported_entries_stay_unsupported");
	for (archive_index = 0; archive_index < (int) (sizeof(stuffit_archives) / sizeof(stuffit_archives[0])); archive_index++) {
		std::vector<unsigned char> archive_data;
		stuffit_manifest_t manifest;
		sti2_entry_list_t list;
		int i;

		if (load_archive_and_manifest(stuffit_archives[archive_index], &archive_data,
		                              &list, &manifest) < 0) {
			FAIL("could not load archive or manifest");
			return 0;
		}
		for (i = 0; i < manifest.num_entries; i++) {
			char temp_name[256];
			char actual_path[1024];
			int index;

			if (manifest.entries[i].is_dir || manifest.entries[i].is_resource)
				continue;
			index = sti2_find_entry_index(&list, manifest.entries[i].path);
			if (index < 0) {
				FAIL("manifest data entry missing from listing");
				return 0;
			}
			if (is_supported_stuffit_method(list.entries[index].data_method))
				continue;
			unsupported_count++;
			sanitize_name(manifest.entries[i].path, temp_name, sizeof(temp_name));
			snprintf(actual_path, sizeof(actual_path), "test_stuffit_unsupported_%d_%s.bin",
			         archive_index, temp_name);
			if (sti2_extract_entry(archive_data.data(), archive_data.size(),
			                       &list.entries[index], actual_path) >= 0) {
				remove(actual_path);
				FAIL("unsupported entry unexpectedly extracted");
				return 0;
			}
			remove(actual_path);
		}
	}
	PASS();
	return 1;
}

static int run_manifest_resource_test(void)
{
	int archive_index;

	TEST("stuffit_resource_entries_are_documented");
	for (archive_index = 0; archive_index < (int) (sizeof(stuffit_archives) / sizeof(stuffit_archives[0])); archive_index++) {
		char manifest_path[1024];
		stuffit_manifest_t manifest;
		int i;
		int resource_count = 0;
		int expect_resources = strstr(stuffit_archives[archive_index], ".win.") == NULL;

		if (build_manifest_path(manifest_path, sizeof(manifest_path), stuffit_archives[archive_index]) < 0 ||
		    manifest_load(manifest_path, &manifest) < 0) {
			FAIL("could not load manifest");
			return 0;
		}
		for (i = 0; i < manifest.num_entries; i++) {
			if (manifest.entries[i].is_resource)
				resource_count++;
		}
		if ((expect_resources && resource_count == 0) ||
		    (!expect_resources && resource_count != 0)) {
			FAIL("resource manifest coverage mismatch");
			return 0;
		}
	}
	PASS();
	return 1;
}

static int run_manifest_method13_test(void)
{
	int archive_index;
	int method13_count = 0;

	TEST("stuffit_method13_hashes_match_manifest");
	for (archive_index = 0; archive_index < (int) (sizeof(stuffit_method13_archives) / sizeof(stuffit_method13_archives[0])); archive_index++) {
		std::vector<unsigned char> archive_data;
		stuffit_manifest_t manifest;
		int i;

		if (load_archive_and_manifest_only(stuffit_method13_archives[archive_index], &archive_data,
		                                   &manifest) < 0) {
			FAIL("could not load method 13 archive or manifest");
			return 0;
		}
		for (i = 0; i < manifest.num_entries; i++) {
			char temp_name[256];
			char actual_path[1024];
			char actual_sha256[STUFFIT_SHA256_HEX_LEN + 1];
			sti2_entry_t entry;
			int written;

			if (manifest.entries[i].is_dir ||
			    manifest.entries[i].is_resource ||
			    !manifest.entries[i].has_method || manifest.entries[i].method != 13u ||
			    !manifest.entries[i].has_archive_data_offset ||
			    !manifest.entries[i].has_archive_data_length ||
			    !manifest.entries[i].sha256[0])
				continue;

			method13_count++;
			build_manifest_driven_entry(&manifest.entries[i], &entry);
			sanitize_name(manifest.entries[i].path, temp_name, sizeof(temp_name));
			snprintf(actual_path, sizeof(actual_path), "test_stuffit_m13_%d_%s_%s.bin",
			         archive_index, manifest.entries[i].is_resource ? "resource" : "file", temp_name);
			written = sti2_extract_entry(archive_data.data(), archive_data.size(), &entry, actual_path);
			if (written < 0 || (unsigned int) written != manifest.entries[i].size ||
			    sha256_file(actual_path, actual_sha256) < 0 ||
			    strcmp(actual_sha256, manifest.entries[i].sha256) != 0) {
				remove(actual_path);
				FAIL("method 13 entry hash mismatch");
				return 0;
			}
			remove(actual_path);
		}
	}
	if (method13_count == 0) {
		FAIL("no method 13 entries checked");
		return 0;
	}
	PASS();
	return 1;
}

int main(void)
{
	int ok = 1;

	printf("StuffIt corpus tests\n");

	if (!run_manifest_fixture_test())
		ok = 0;
	if (!run_manifest_listing_test())
		ok = 0;
	if (!run_manifest_supported_hash_test())
		ok = 0;
	if (!run_manifest_method13_test())
		ok = 0;
	if (!run_manifest_unsupported_test())
		ok = 0;
	if (!run_manifest_resource_test())
		ok = 0;

	printf("\nSummary: %d passed, %d total\n", tests_passed, tests_run);
	return ok ? 0 : 1;
}
