#!/usr/bin/env pwsh
# generate_game_data_index.ps1 -- Build a SHA-256 hash index of local game data files.
#
# Scans local game data directories for game asset files and writes
# game_data/game_data_index.txt with format:  <sha256>  <relative-path>
# Paths are relative to the repo root. Only the first (highest-priority)
# path per hash is kept. Used by test infrastructure to resolve declarative
# game data dependencies.
#
# Usage:  .\generate_game_data_index.ps1

$ErrorActionPreference = "Stop"

$ScriptDir = $PSScriptRoot
$RepoRoot  = Split-Path $ScriptDir
$OutFile   = Join-Path $ScriptDir "game_data_index.txt"

$GameExtensions = @(".hog", ".pig", ".ham", ".mvl", ".s11", ".s22", ".mn2", ".gog", ".inst", ".exe", ".dxa")

# Search directories in priority order (first match per hash wins)
$SearchDirs = @(
    (Join-Path $RepoRoot "game_data_to_copy_to_emulator\temp"),
    (Join-Path $RepoRoot "game_data_to_copy_to_emulator\data"),
    (Join-Path $RepoRoot "game_data\gog installers"),
    (Join-Path $RepoRoot "game_data\extracted\VERTIGO"),
    (Join-Path $RepoRoot "game_data\extracted\d1 mac extracted"),
    (Join-Path $RepoRoot "game_data\extracted\d2_mac_demo"),
    (Join-Path $RepoRoot "game_data\extracted\descent 1 demo 1-4_extracted"),
    (Join-Path $RepoRoot "game_data\extracted\descent 2 demo 1-0_extracted"),
    (Join-Path $RepoRoot "game_data\mods")
)

# hash -> relative path (first seen wins)
$index = [ordered]@{}
$fileCount = 0

foreach ($dir in $SearchDirs) {
    if (-not (Test-Path $dir)) { continue }
    $files = Get-ChildItem $dir -File -Recurse -ErrorAction SilentlyContinue |
        Where-Object { $GameExtensions -contains $_.Extension.ToLower() -and $_.Length -gt 1 }
    foreach ($f in $files) {
        $hash = (Get-FileHash $f.FullName -Algorithm SHA256).Hash.ToLower()
        if (-not $index.Contains($hash)) {
            $relPath = $f.FullName.Substring($RepoRoot.Length + 1).Replace('\', '/')
            $index[$hash] = $relPath
            $fileCount++
        }
    }
}

# Write index file
$lines = @("# game_data_index.txt -- SHA-256 hash index of local game data files",
           "# Generated by generate_game_data_index.ps1 -- do not edit manually",
           "# Format: <sha256>  <relative-path-from-repo-root>",
           "")
foreach ($hash in $index.Keys) {
    $lines += "$hash  $($index[$hash])"
}
$lines += ""
Set-Content -Path $OutFile -Value ($lines -join "`n") -NoNewline -Encoding UTF8

Write-Host "Wrote $fileCount entries to $OutFile"
