plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'org.jetbrains.kotlin.plugin.serialization'
}

def toolVersions = new Properties()
toolVersions.load(new FileInputStream(rootProject.file('get_deps/tool_versions.conf')))

kotlin {
    jvmToolchain(21)
}

dependencies {
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:${toolVersions['KOTLINX_SERIALIZATION_VERSION']}"
    testImplementation "junit:junit:${toolVersions['JUNIT_VERSION']}"
}

tasks.withType(Test).configureEach {
    useJUnit()
}
