#!/bin/bash
# build-aab.sh - Build an AAB with all ABIs and copy to build-outputs/
# Usage: ./build-aab.sh [--release] [--clean]
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# Prompt for build type
echo ""
echo "Select build type:"
echo "  1) Debug"
echo "  2) Release (signed, for Play Console)"
echo ""
printf "Enter choice [2]: "
read -r CHOICE
if [ "$CHOICE" = "1" ]; then
    VARIANT="debug"
else
    VARIANT="release"
fi

# Source environment variables
source "$SCRIPT_DIR/set_vars.sh"

TASK="bundle$(echo "$VARIANT" | sed 's/.*/\u&/')"

VERSION_CODE=$(git rev-list --count HEAD)
GIT_HASH=$(git rev-parse --short HEAD)
BUILD_DATE=$(date +"%Y-%m-%d")
BUILD_TIME=$(TZ='America/Los_Angeles' date +"%H:%M")
echo ""
echo "versionCode: $VERSION_CODE (git commits)"
echo "gitHash:     $GIT_HASH"
echo "buildDate:   $BUILD_DATE"
echo "buildTime:   $BUILD_TIME PST"

# Generate BuildInfo.kt with real build metadata
BUILD_INFO="app/src/main/java/com/dxxredux/app/BuildInfo.kt"
cat > "$BUILD_INFO" <<EOF
package com.dxxredux.app

/**
 * Build metadata - regenerated by build-aab.ps1 / build-aab.sh before release builds.
 * For local dev builds this contains placeholder values.
 *
 * DO NOT EDIT MANUALLY - the build scripts overwrite this file.
 */
object BuildInfo {
    const val GIT_COMMIT_COUNT = "$VERSION_CODE"
    const val GIT_SHORT_HASH   = "$GIT_HASH"
    const val BUILD_DATE       = "$BUILD_DATE"
    const val BUILD_TIME       = "$BUILD_TIME PST"
    const val BUILD_TYPE       = "$VARIANT"
}
EOF
echo "Generated: $BUILD_INFO"

# Ensure Gradle wrapper exists (not in VCS -- generated by get_deps/get_gradle_wrapper.sh)
if [ ! -f gradle/wrapper/gradle-wrapper.jar ] || [ ! -f gradle/wrapper/gradle-wrapper.properties ]; then
    echo "Gradle wrapper not found -- running get_gradle_wrapper.sh..."
    bash get_deps/get_gradle_wrapper.sh
fi

echo ""
echo "Building AAB ($VARIANT) for armeabi-v7a, arm64-v8a, x86_64..."
echo ""
./gradlew "$TASK"

# Find the AAB
AAB_DIR="app/build/outputs/bundle/$VARIANT"
AAB=$(find "$AAB_DIR" -name '*.aab' -print -quit 2>/dev/null)
if [ -z "$AAB" ]; then
    echo "ERROR: AAB not found in $AAB_DIR" >&2
    exit 1
fi

# Copy to build-outputs/ with timestamp
OUT_DIR="build-outputs"
mkdir -p "$OUT_DIR"

TIMESTAMP=$(date +"%Y%m%d-%H%M%S")
OUT_NAME="dxx-redux-${VARIANT}-${TIMESTAMP}-v${VERSION_CODE}.aab"
OUT_PATH="$OUT_DIR/$OUT_NAME"

cp "$AAB" "$OUT_PATH"
SIZE=$(du -h "$OUT_PATH" | cut -f1)

echo ""
echo "AAB built successfully: $OUT_PATH ($SIZE)"
echo ""
echo "Press any key to exit..."
read -r -n1 -s
