#!/usr/bin/env pwsh
# Build a Play AAB and signed universal direct-install APK and copy to build-outputs/
# Usage: .\android\1_build_aab_apk.ps1 [[-BuildType] <string>]
#        .\android\1_build_aab_apk.ps1 -BuildType "2"  # Release signing
# OutputPath specifies the AAB destination; the APK is a sibling named <basename>-universal.apk
# Release/Internal use keystore.properties; Debug uses the Android debug key
# Release/Internal APKs use the GitHub distribution ID so they can coexist with Play installs

param(
    [ValidateSet('1', '2', '3')][string]$BuildType,
    [string]$VersionCode,   # Override version code (commit_count*10+rev). Default: commit_count*10
    [string]$OutputPath
)

$ErrorActionPreference = "Stop"
$repoRoot = Split-Path $PSScriptRoot
. (Join-Path $PSScriptRoot "helpers/test_host_platform.ps1")

function Read-NumberedChoice {
    param(
        [string]$Prompt,
        [int]$OptionCount,
        [int]$DefaultChoice = 1
    )

    while ($true) {
        $choice = Read-Host $Prompt
        if ([string]::IsNullOrWhiteSpace($choice)) {
            return [string]$DefaultChoice
        }

        $selected = 0
        if ([int]::TryParse($choice, [ref]$selected) -and $selected -ge 1 -and $selected -le $OptionCount) {
            return [string]$selected
        }

        Write-Host "Enter a number between 1 and $OptionCount" -ForegroundColor Yellow
    }
}

Initialize-RegressionJavaEnvironment -RepoRoot $repoRoot

# Prompt for build type (or use parameter)
Write-Host ""
if (-not $BuildType) {
    Write-Host "Select build type:"
    Write-Host "  1) Debug"
    Write-Host "  2) Release (signed, for Play Console)"
    Write-Host "  3) Internal (debug + release signing, for Play internal testing)"
    Write-Host ""
    $BuildType = Read-NumberedChoice -Prompt "Enter choice (1-3)" -OptionCount 3
}
if (-not $BuildType) { $BuildType = "1" }

if ($BuildType -eq '1') {
    $variant = "Debug"
} elseif ($BuildType -eq '3') {
    $variant = "Internal"
} else {
    $variant = "Release"
}
if ($variant -ne 'Debug' -and -not (Test-Path -LiteralPath (Join-Path $PSScriptRoot 'keystore.properties') -PathType Leaf)) {
    throw 'Release/Internal signing requires android/keystore.properties'
}
$toolVersionsPath = Join-Path $PSScriptRoot 'get_deps/tool_versions.conf'
$buildToolsVersion = (Select-String -LiteralPath $toolVersionsPath -Pattern '^BUILD_TOOLS_VERSION=(.+)$').Matches.Groups[1].Value
if (-not $buildToolsVersion) { throw "BUILD_TOOLS_VERSION pin missing in $toolVersionsPath" }
$signerName = if (Test-RegressionWindowsHost) { 'apksigner.bat' } else { 'apksigner' }
$apkSigner = Resolve-RegressionAndroidSdkTool -DepBase (Get-RegressionDependencyBase -RepoRoot $repoRoot) `
    -Subdir "build-tools/$buildToolsVersion" -ToolName $signerName
if (-not (Test-Path -LiteralPath $apkSigner -PathType Leaf)) { throw "APK signing tool not found: $apkSigner" }
$aapt = Resolve-RegressionAndroidSdkTool -DepBase (Get-RegressionDependencyBase -RepoRoot $repoRoot) `
    -Subdir "build-tools/$buildToolsVersion" -ToolName aapt2
if (-not (Test-Path -LiteralPath $aapt -PathType Leaf)) { throw "APK inspection tool not found: $aapt" }

$commitCount = (git -C $repoRoot rev-list --count HEAD).Trim()
if ($VersionCode) {
    $versionCode = $VersionCode
} else {
    $versionCode = [int]$commitCount * 10
}
$gitHash = (git -C $repoRoot rev-parse --short HEAD).Trim()
$builtAtUtc = [DateTime]::UtcNow
$buildDate = $builtAtUtc.ToString('yyyy-MM-dd')
$buildTime = $builtAtUtc.ToString('HH:mm')
Write-Host ""
Write-Host "commitCount: $commitCount (# of git commits)"
Write-Host "versionCode: $versionCode (commitCount*10 + rev)"
Write-Host "gitHash:     $gitHash"
Write-Host "buildDate:   $buildDate"
Write-Host "buildTime:   $buildTime UTC"

$variantLower = $variant.ToLower()
# Copy to build-outputs/ with timestamp
$outDir = Join-Path $PSScriptRoot "build-outputs"
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir | Out-Null }

if ($OutputPath) {
    $outPath = if ([System.IO.Path]::IsPathRooted($OutputPath)) { $OutputPath } else { Join-Path $PSScriptRoot $OutputPath }
    $requestedDir = Split-Path -Parent $outPath
    if (-not (Test-Path $requestedDir)) { New-Item -ItemType Directory -Path $requestedDir | Out-Null }
} else {
    $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $outName = "dxx-redux-$variantLower-$timestamp-v$versionCode.aab"
    $outPath = Join-Path $outDir $outName
}

$apkOutPath = Join-Path (Split-Path -Parent $outPath) "$([IO.Path]::GetFileNameWithoutExtension($outPath))-universal.apk"
& (Join-Path $PSScriptRoot "helpers\retain-recent-artifacts.ps1") -Artifacts @($outPath, $apkOutPath)

# Generate BuildInfo.kt with real build metadata
$buildInfoPath = Join-Path $PSScriptRoot "app\src\main\java\com\dxxredux\app\BuildInfo.kt"
$buildInfoContent = @"
package com.dxxredux.app

/**
 * Build metadata -- regenerated by 1_build_aab_apk.ps1 before release builds.
 * For local dev builds this contains placeholder values.
 *
 * DO NOT EDIT MANUALLY -- the build scripts overwrite this file.
 */
object BuildInfo {
    const val GIT_COMMIT_COUNT = "$versionCode"
    const val GIT_SHORT_HASH = "$gitHash"
    const val BUILD_DATE = "$buildDate"
    const val BUILD_TIME = "$buildTime UTC"
    const val BUILD_TYPE = "$($variant.ToLower())"
}
"@
[IO.File]::WriteAllText($buildInfoPath, $buildInfoContent + [Environment]::NewLine, [Text.UTF8Encoding]::new($false))
Write-Host "Generated: $buildInfoPath"

# Ensure Gradle wrapper exists (not in VCS -- generated by get_deps/helpers/get_gradle_wrapper.sh)
$gradleWrapperJar = Join-Path $PSScriptRoot "gradle\wrapper\gradle-wrapper.jar"
$gradleWrapperProps = Join-Path $PSScriptRoot "gradle\wrapper\gradle-wrapper.properties"
if (-not (Test-Path $gradleWrapperJar) -or -not (Test-Path $gradleWrapperProps)) {
    Write-Host "Gradle wrapper not found -- running get_gradle_wrapper.sh..."
    $prevEAP = $ErrorActionPreference; $ErrorActionPreference = "Continue"
    $env:GET_ALL_RUNNING = "1"
    & bash (Join-Path $PSScriptRoot "get_deps\helpers\get_gradle_wrapper.sh") 2>&1 | ForEach-Object { "$_" }
    $env:GET_ALL_RUNNING = $null
    $ErrorActionPreference = $prevEAP
    if (-not (Test-Path $gradleWrapperJar)) {
        throw "Failed to bootstrap Gradle wrapper. Run get_deps\helpers\get_gradle_wrapper.sh manually"
    }
}

Write-Host ""
Write-Host "Building Play AAB ($variant) for armeabi-v7a, arm64-v8a, x86_64..."
Write-Host ""
$gradle = Resolve-RegressionGradleWrapper -AndroidDir $PSScriptRoot
$commonProperties = @('-PskipBuildInfo', "-PversionCodeOverride=$versionCode", '-PlegacyRelease=false', '-PciApk=false')
# Play signs installed apps with its app key; the local upload key cannot update them
# Select each distribution explicitly, even if gradle.properties has local defaults
& $gradle -p $PSScriptRoot "bundle$variant" @commonProperties '-PgithubRelease=false'
if ($LASTEXITCODE -ne 0) { throw "Gradle build failed with exit code $LASTEXITCODE" }

# Find the AAB
$variantLower = $variant.ToLower()
$aabDir = Join-Path $PSScriptRoot "app\build\outputs\bundle\$variantLower"
$aab = Get-ChildItem "$aabDir\*.aab" -ErrorAction SilentlyContinue | Select-Object -First 1
if (-not $aab) { throw "AAB not found in $aabDir" }

$directInstall = $variant -ne 'Debug'
$apkPackage = if ($directInstall) { 'com.dxxredux.app.github' } else { 'com.dxxredux.app' }
Write-Host "Building universal APK ($variant, $apkPackage)..."
# Native compilation is reused; JVM sources and the manifest differ between distributions
& $gradle -p $PSScriptRoot "assemble$variant" @commonProperties "-PgithubRelease=$($directInstall.ToString().ToLowerInvariant())"
if ($LASTEXITCODE -ne 0) { throw "Gradle APK build failed with exit code $LASTEXITCODE" }

$apkPath = Join-Path $PSScriptRoot "app/build/outputs/apk/$variantLower/app-$variantLower.apk"
if (-not (Test-Path -LiteralPath $apkPath -PathType Leaf)) { throw "Signed APK not found: $apkPath" }
& $apkSigner verify $apkPath
if ($LASTEXITCODE -ne 0) { throw 'APK signature verification failed' }
$badging = (& $aapt dump badging $apkPath) -join "`n"
if ($LASTEXITCODE -ne 0 -or $badging -notmatch "package: name='$([regex]::Escape($apkPackage))' versionCode='$versionCode'") {
    throw "APK package/version mismatch; expected $apkPackage versionCode $versionCode"
}

# Reject a split APK or an artifact missing either game engine
Add-Type -AssemblyName System.IO.Compression.FileSystem
$archive = [IO.Compression.ZipFile]::OpenRead($apkPath)
try {
    foreach ($abi in @('armeabi-v7a', 'arm64-v8a', 'x86_64')) {
        foreach ($library in @('libdxx-redux-d1.so', 'libdxx-redux-d2.so')) {
            if (-not $archive.GetEntry("lib/$abi/$library")) { throw "APK lacks $abi/$library" }
        }
    }
} finally {
    $archive.Dispose()
}

Copy-Item -LiteralPath $aab.FullName -Destination $outPath -Force
Copy-Item -LiteralPath $apkPath -Destination $apkOutPath -Force
$aabSizeMB = [math]::Round((Get-Item -LiteralPath $outPath).Length / 1MB, 1)
$apkSizeMB = [math]::Round((Get-Item -LiteralPath $apkOutPath).Length / 1MB, 1)

Write-Host ""
Write-Host "AAB built successfully: $outPath ($aabSizeMB MB)"
Write-Host "Signed universal APK built successfully: $apkOutPath ($apkSizeMB MB)"
Write-Host "APK application ID: $apkPackage"
if ($directInstall) {
    Write-Host 'Install the APK alongside Google Play; updates to this APK require the same signing key'
} else {
    Write-Host 'Debug APK uses the development package/key and can conflict with a Play installation'
}
Write-Host ""
