# build-aab.ps1 — Build an AAB with all ABIs and copy to build-outputs/
# Usage: .\build-aab.ps1

$ErrorActionPreference = "Stop"

Push-Location $PSScriptRoot
try {
    # Set JAVA_HOME if not already set
    if (-not $env:JAVA_HOME) {
        $_depBaseFile = Join-Path (Split-Path $PSScriptRoot) "dependency_base.txt"
        if (-not (Test-Path $_depBaseFile)) {
            Write-Error "dependency_base.txt not found at $_depBaseFile. Create it with a single line containing the path to your dependency directory (e.g. C:\local)."
            exit 1
        }
        $DEP_BASE = (Get-Content $_depBaseFile -First 1).Trim()
        $jdk = Get-ChildItem "$DEP_BASE\jdk-*" -Directory | Sort-Object Name -Descending | Select-Object -First 1
        if ($jdk) {
            $env:JAVA_HOME = $jdk.FullName
            Write-Host "JAVA_HOME = $env:JAVA_HOME"
        } else {
            Write-Error "No JDK found in $DEP_BASE\jdk-*. Set JAVA_HOME manually."
        }
    }

    # Prompt for build type
    Write-Host ""
    Write-Host "Select build type:"
    Write-Host "  1) Debug"
    Write-Host "  2) Release (signed, for Play Console)"
    Write-Host ""
    $choice = Read-Host "Enter choice [2]"
    if ($choice -eq '1') {
        $variant = "Debug"
    } else {
        $variant = "Release"
    }
    $task = "bundle$variant"

    $versionCode = (git rev-list --count HEAD).Trim()
    $gitHash = (git rev-parse --short HEAD).Trim()
    $buildDate = Get-Date -Format "yyyy-MM-dd"
    $buildTime = [System.TimeZoneInfo]::ConvertTimeBySystemTimeZoneId((Get-Date), 'Pacific Standard Time').ToString('HH:mm')
    Write-Host ""
    Write-Host "versionCode: $versionCode (git commits)"
    Write-Host "gitHash:     $gitHash"
    Write-Host "buildDate:   $buildDate"
    Write-Host "buildTime:   $buildTime PST"

    # Generate BuildInfo.kt with real build metadata
    $buildInfoPath = "app\src\main\java\com\dxxredux\app\BuildInfo.kt"
    $buildInfoContent = @"
package com.dxxredux.app

/**
 * Build metadata — regenerated by build-aab.ps1 / build-aab.sh before release builds.
 * For local dev builds this contains placeholder values.
 *
 * DO NOT EDIT MANUALLY — the build scripts overwrite this file.
 */
object BuildInfo {
    const val GIT_COMMIT_COUNT = "$versionCode"
    const val GIT_SHORT_HASH   = "$gitHash"
    const val BUILD_DATE       = "$buildDate"
    const val BUILD_TIME       = "$buildTime PST"
    const val BUILD_TYPE       = "$($variant.ToLower())"
}
"@
    Set-Content -Path $buildInfoPath -Value $buildInfoContent -Encoding UTF8
    Write-Host "Generated: $buildInfoPath"

    Write-Host ""
    Write-Host "Building AAB ($variant) for armeabi-v7a, arm64-v8a, x86_64..."
    Write-Host ""
    & .\gradlew.bat $task
    if ($LASTEXITCODE -ne 0) { throw "Gradle build failed with exit code $LASTEXITCODE" }

    # Find the AAB
    $variantLower = $variant.ToLower()
    $aabDir = "app\build\outputs\bundle\$variantLower"
    $aab = Get-ChildItem "$aabDir\*.aab" -ErrorAction SilentlyContinue | Select-Object -First 1
    if (-not $aab) { throw "AAB not found in $aabDir" }

    # Copy to build-outputs/ with timestamp
    $outDir = "build-outputs"
    if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir | Out-Null }

    $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $outName = "dxx-redux-$variantLower-$timestamp-v$versionCode.aab"
    $outPath = Join-Path $outDir $outName

    Copy-Item $aab.FullName $outPath
    $sizeMB = [math]::Round((Get-Item $outPath).Length / 1MB, 1)

    Write-Host ""
    Write-Host "AAB built successfully: $outPath ($sizeMB MB)"
    Write-Host ""
} finally {
    Pop-Location
}
