"""Audit every regression level and summarize uncapped fly-out timings."""

import argparse
import collections
import csv
import json
import math
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    repo = Path(__file__).resolve().parents[2]
    root = repo / "game_data" / "mission_files"
    files = sorted(root.glob("*.json")) + sorted((root / "d2xxl_downloads").glob("*.json"))
    rows, problems = [], []
    mission_count = 0
    for path in files:
        # Route-simulation companions are generated by a different runner
        if path.name.endswith(".simulation.json"):
            continue
        document = json.loads(path.read_text(encoding="utf-8-sig"))
        missions = document if isinstance(document, list) else [document]
        for mission in missions:
            if not isinstance(mission, dict) or "levels" not in mission:
                continue
            mission_count += 1
            for level in mission["levels"]:
                identity = f"{path.name}/{mission.get('mission_filename', '')}/{level.get('level_num')}"
                flyout = level.get("flyout")
                if not isinstance(flyout, dict):
                    problems.append(f"{identity}: missing flyout record")
                    continue
                seconds = flyout.get("seconds")
                kind, status = flyout.get("kind"), flyout.get("status")
                if kind not in ("none", "in_engine", "video") or not status or "seconds" not in flyout:
                    problems.append(f"{identity}: incomplete flyout record")
                if seconds is not None and (
                    isinstance(seconds, bool) or not isinstance(seconds, (int, float))
                    or not math.isfinite(seconds) or seconds <= 0
                ):
                    problems.append(f"{identity}: invalid duration {seconds}")
                if status in ("estimated", "measured") and seconds is None:
                    problems.append(f"{identity}: timing status without duration")
                if status != "level_not_loaded":
                    for component in ("movie", "tunnel", "presentation"):
                        if not flyout.get(component, {}).get("status"):
                            problems.append(f"{identity}: missing {component} status")
                    if flyout.get("exit_trigger") not in ("present", "absent"):
                        problems.append(f"{identity}: missing exit trigger status")
                    tunnel = flyout.get("tunnel", {})
                    if (status == "estimated") != (tunnel.get("seconds") is not None):
                        problems.append(f"{identity}: tunnel timing disagrees with availability")
                if status != "estimated":
                    if any("seconds" in route or "tunnel_units" in route for route in flyout.get("routes", [])):
                        problems.append(f"{identity}: unused geometry estimate published")
                    if status != "measured" and (kind != "none" or seconds is not None):
                        problems.append(f"{identity}: unavailable flyout has a duration or playback kind")
                if kind == "in_engine":
                    timings = [route["seconds"] for route in flyout.get("routes", []) if route.get("seconds") is not None]
                    if seconds is not None and (not timings or seconds != max(timings)):
                        problems.append(f"{identity}: top-level time is not the longest exit")
                rows.append({
                    "regression": str(path.relative_to(repo)).replace("\\", "/"),
                    "mission": mission.get("mission_name", ""),
                    "game": mission.get("game", ""),
                    "level": level.get("level_num"),
                    "level_file": level.get("level_file", ""),
                    "kind": kind, "status": status, "seconds": seconds,
                    "movie": flyout.get("movie", {}).get("status", "not_inspected"),
                    "exit_trigger": flyout.get("exit_trigger", "not_inspected"),
                    "tunnel": flyout.get("tunnel", {}).get("status", "not_inspected"),
                    "presentation": flyout.get("presentation", {}).get("status", "not_inspected"),
                    "route_statuses": ",".join(route["status"] for route in flyout.get("routes", [])),
                })
    args.output.parent.mkdir(parents=True, exist_ok=True)
    summary = {
        "missions": mission_count,
        "levels_with_flyout_records": len(rows),
        "problems": problems,
        "statuses": dict(sorted(collections.Counter(row["status"] for row in rows).items())),
        "in_engine_route_statuses": dict(sorted(collections.Counter(
            status for row in rows for status in row["route_statuses"].split(",") if status
        ).items())),
        "components": {field: dict(sorted(collections.Counter(row[field] for row in rows).items()))
                       for field in ("movie", "exit_trigger", "tunnel", "presentation")},
        "timings": {},
    }
    for label, subset in (
        ("in_engine_with_present_assets", [r for r in rows if r["status"] == "estimated"]),
        ("measured_videos", [r for r in rows if r["status"] == "measured"]),
    ):
        ordered = sorted(subset, key=lambda r: r["seconds"])
        summary["timings"][label] = {
            "count": len(ordered),
            "min_seconds": ordered[0]["seconds"] if ordered else None,
            "max_seconds": ordered[-1]["seconds"] if ordered else None,
            "over_20_seconds": sum(r["seconds"] > 20 for r in ordered),
            "over_60_seconds": sum(r["seconds"] > 60 for r in ordered),
            "longest": list(reversed(ordered[-10:])),
        }
    args.output.write_text(json.dumps(summary, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")
    if rows:
        with args.output.with_suffix(".csv").open("w", newline="", encoding="utf-8") as out:
            writer = csv.DictWriter(out, fieldnames=list(rows[0]))
            writer.writeheader()
            writer.writerows(rows)
    print(json.dumps({k: v for k, v in summary.items() if k != "timings"}, indent=2))
    if problems:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
