// Generated by android/tests/fit_music_eq.py --publish; do not edit
#ifndef DXX_MUSIC_EQ_PRESETS_H
#define DXX_MUSIC_EQ_PRESETS_H
#include <cstdint>
constexpr uint64_t music_eq_font_fnv = UINT64_C(0x4aa25f43660b41c8);
constexpr size_t music_eq_font_bytes = 10375822;
struct music_eq_band {
	int type;
	double frequency, gain, width;
};
struct music_eq_profile {
	double preamp;
	music_eq_band bands[5];
};
constexpr music_eq_profile music_eq_profiles[] = {
	{ -0.0848603767517, {
	                        { 0, 112.770074644, -9.10269685442, 1 },
	                        { 1, 200, -0.531006957914, 1.4 },
	                        { 1, 800, 0.256896075435, 0.3 },
	                        { 1, 4331.89151616, -3.18217260588, 0.713017948403 },
	                        { 2, 9203.10179317, -3.29451232765, 1 },
	                    } },
	{ -0.0757537032064, {
	                        { 0, 118.298851464, -8.34901979645, 1 },
	                        { 1, 200, -0.694861371923, 1.2177160473 },
	                        { 1, 800.000000012, 0.331981296279, 0.300000000044 },
	                        { 1, 4579.50312847, -2.90380742894, 0.517122845382 },
	                        { 2, 9332.2139343, -2.73837468725, 1 },
	                    } },
	{ -0, {
	          { 0, 122.295642691, -7.14873124279, 1 },
	          { 1, 200, -1.31077767211, 0.906008039852 },
	          { 1, 800.000000244, 0.273406335095, 0.300000000186 },
	          { 1, 6132.16002745, -2.68890218277, 0.3 },
	          { 2, 9658.90364487, -1.30442825358, 1 },
	      } },
};
#endif
