"""Regenerate the test-only Guidebot oracle from its pinned Redux Git object.

Run from any working directory, then clang-format the generated C/header files.
Function bodies remain frozen inside a clang-format exclusion block.
"""

from pathlib import Path
import re
import subprocess


PIN = "9fd90f03513663ce1372c8cfa723b7a73c4219fa"
ROOT = Path(__file__).resolve().parents[2]
FUNCTIONS = {
    "escort.c": """
        segment_is_reachable create_bfs_list exists_in_mine_2 exists_in_mine
        find_exit_segment get_boss_id escort_create_path_to_goal
        escort_set_goal_object time_to_visit_player do_escort_frame
        marker_exists_in_mine set_escort_special_goal detect_escort_goal_accomplished
    """.split(),
    "aipath.c": """
        create_random_xlate insert_center_points move_towards_outside
        create_path_points polish_path create_path_to_player create_path_to_segment
        create_path_to_station create_n_segment_path move_object_to_goal
        ai_follow_path ai_path_set_orient_and_vel
    """.split(),
    "ai2.c": ["ai_door_is_openable"],
}
HEADERS = """
    inferno console 3d object dxxerror ai robot fvi physics wall player fireball
    game escort key powerup cntrlcen text weapon gameseg gameseq gauges playsave
    digi sounds
""".split()


def extract(source, name):
    """Extract a complete function, ignoring braces inside comments and strings."""
    match = re.search(
        r"^([\w *\t]+\b" + re.escape(name) + r"\([^;]*?\))\s*\{", source, re.M
    )
    if not match:
        raise ValueError(f"Missing reference function: {name}")
    start = match.end() - 1
    tokens = re.finditer(
        r'/\*.*?\*/|//[^\n]*|"(?:\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\'|[{}]',
        source[start:],
        re.S,
    )
    depth = 0
    for token in tokens:
        if token.group() == "{":
            depth += 1
        elif token.group() == "}":
            depth -= 1
            if depth == 0:
                return match.group(1), source[match.start() : start + token.end()]
    raise ValueError(f"Unterminated reference function: {name}")


def rename(source):
    names = [name for group in FUNCTIONS.values() for name in group]
    return re.sub(
        r"\b(" + "|".join(names) + r")\b",
        lambda match: "redux_" + match.group(),
        source,
    )


PRELUDE = """
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define PARALLAX 0
#define PATH_VALIDATION 0
#define AVOID_SEG_LENGTH 7
#define MAX_ESCORT_TIME_AWAY (4*F1_0)
extern int Last_buddy_polish_path_tick;
extern int Max_escort_length, Escort_kill_object;
extern int Looking_for_marker, Last_buddy_key, Buddy_messages_suppressed;
extern fix64 Last_buddy_message_time, Buddy_last_seen_player, Buddy_last_player_path_created;
extern fix64 Last_come_back_message_time, Buddy_sorry_time;
extern int ok_for_buddy_to_talk(void);
extern void say_escort_goal(int);
extern void do_buddy_dude_stuff(void);
extern void maybe_ai_path_garbage_collect(void);
extern void ai_path_garbage_collect(void);
"""


def main():
    sources = {
        filename: subprocess.check_output(
            ["git", "show", f"{PIN}:d2/main/{filename}"], cwd=ROOT
        ).decode("utf-8")
        for filename in FUNCTIONS
    }
    parts = [
        extract(sources[filename], name)
        for filename, names in FUNCTIONS.items()
        for name in names
    ]
    escort = sources["escort.c"]
    license_text = escort[: escort.index("*/") + 2]
    includes = "\n".join(f'#include "{name}.h"' for name in HEADERS)
    goal_text = re.search(
        r"static const char \*const Escort_goal_text\[MAX_ESCORT_GOALS\] = \{.*?\};",
        escort,
        re.S,
    )
    if not goal_text:
        raise ValueError("Missing reference goal labels")
    header = (
        "/* Test-only pinned Redux declarations; see guidebot_redux_reference.c */\n"
        '#pragma once\n#include "ai.h"\n'
        + rename("\n".join(signature + ";" for signature, _ in parts))
        + "\n"
    )
    body = (
        license_text
        + f"\n/* Frozen routing oracle from dxx-redux/dxx-redux {PIN}\n"
        " * Only function symbols are prefixed; engine geometry/math are shared\n"
        " * Generated by update_guidebot_redux_reference.py; do not edit this oracle\n"
        " * Fixtures keep paths below the original 200-point temporary capacity */\n"
        + includes
        + PRELUDE
        + "\n"
        + goal_text.group()
        + '\n#include "guidebot_redux_reference.h"\n// clang-format off\n'
        + rename("\n\n".join(function for _, function in parts))
        + "\n// clang-format on\n"
    )
    (ROOT / "android/tests/guidebot_redux_reference.h").write_text(header, encoding="utf-8")
    (ROOT / "android/tests/guidebot_redux_reference.c").write_text(body, encoding="utf-8")


if __name__ == "__main__":
    main()
