package com.dxxredux.app

/**
 * Build metadata â€” regenerated by build-aab.ps1 / build-aab.sh before release builds.
 * For local dev builds this contains placeholder values.
 *
 * DO NOT EDIT MANUALLY â€” the build scripts overwrite this file.
 */
object BuildInfo {
    const val GIT_COMMIT_COUNT = "dev"
    const val GIT_SHORT_HASH   = "dev"
    const val BUILD_DATE       = "dev"
    const val BUILD_TIME       = "dev"
    const val BUILD_TYPE       = "dev"
}
