name: Package - Linux

on:
  #push:
  #  branches: [ master ]

  #pull_request:
  #  branches: [ master ]

  workflow_dispatch:

  workflow_call:

permissions:
  contents: read

jobs:
  linux:
    name: Linux AppImages
    runs-on: ubuntu-22.04
    steps:
      - name: Clone Repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fuse
          sudo apt-get install -y cmake libphysfs-dev libsdl1.2-dev libsdl-mixer1.2-dev libpng-dev libglew-dev

      - name: Configure D1
        run: cmake -S d1 -B buildd1 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DOpenGL_GL_PREFERENCE=LEGACY

      - name: Build D1
        run: cmake --build buildd1 --parallel 4

      - name: Test D1
        env:
          SDL_AUDIODRIVER: dummy
          SDL_VIDEODRIVER: dummy
        run: ctest --test-dir buildd1 --output-on-failure

      - name: Configure D2
        run: cmake -S d2 -B buildd2 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DOpenGL_GL_PREFERENCE=LEGACY

      - name: Build D2
        run: cmake --build buildd2 --parallel 4

      - name: Test D2
        env:
          SDL_AUDIODRIVER: dummy
          SDL_VIDEODRIVER: dummy
        run: ctest --test-dir buildd2 --output-on-failure

      - name: Package AppImage
        run: ./contrib/packaging/linux/build_package.sh

      - name: Upload artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: linux
          path: '*.tar.gz'
          if-no-files-found: error
