name: Package - All

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  linux:
    uses: ./.github/workflows/package-linux.yml
  windows:
    uses: ./.github/workflows/package-windows.yml
  msvc:
    uses: ./.github/workflows/package-msvc.yml
  macos:
    uses: ./.github/workflows/package-macos.yml
  macos-arm:
    uses: ./.github/workflows/package-macos-arm.yml
